name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.45

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Type Check
        run: deno check *.ts

      - name: Test
        run: deno test --no-check --coverage

      - name: Report
        run: deno coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.45

      - name: Build
        run: deno task build

      - name: Report Size
        run: deno task gzip
