name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.45

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Type Check
        run: deno check *.ts

      - name: Test
        run: deno test --no-check --coverage

      - name: Report
        run: deno coverage

  gzip:
    name: Module Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: gzip (bytes)
        run: |
          bun build --minify mod.ts | bunx terser --mangle --compress --module --ecma=2020 | gzip -9 | wc -c
